---
title: "Variance components for pairs involving Hnf4a"
author: "Frederick Boehm"
date: "10/12/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


We want to infer variance components for all 139 pairs that involve *Hnf4a* in the Chromosome 2 hotspot in the Keller et al 2018 data. 

```{r}
load("../data-to-ignore/Attie_DO378_eQTL_viewer_v1.Rdata")
readRDS("../data/hotspot_expr_tib2_keller_chr2.rds") -> hotspot_expr
readRDS("../data/keller2018-chr2-local-expr.rds") -> local_expr
```

```{r}
# what is the ENSEMBL id for Hnf4a?
hnf4a_id <- "ENSMUSG00000017950"
```


```{r}
library(qtl2)
library(qtl2pleio)
library(tidyverse)
# convert to needed phenotypes input format for scan1
as.matrix(local_expr[, 1:21]) -> local_expr_mat
rownames(local_expr_mat) <- local_expr$mouse_id %>% unlist() %>% as.character()
#
as.matrix(hotspot_expr[, 1:139]) -> hotspot_expr_mat
rownames(hotspot_expr_mat) <- hotspot_expr$mouse_id %>% unlist() %>% as.character()
#
# isolate additive covariates
dataset.islet.rnaseq$covar -> addcovar
addcovar2 <- addcovar[rownames(addcovar) %in% hotspot_expr$mouse_id, ]
```



```{r}
# prepare inputs for calc_covs()
k2 <- K$`2`[rownames(K$`2`) %in% rownames(hotspot_expr_mat), colnames(K$`2`) %in% rownames(hotspot_expr_mat)]

```



```{r}
get_vc <- function(e2, # n by 1 expression matrix for gene 1
                   e1, # n by 1 expression matrix for gene 2
                   kinship, #kinship matrix
                   covariates = NULL # matrix
                   ){
  pheno <- cbind(e1, e2)
  cc_out <- calc_covs(pheno = pheno, 
                      kinship = kinship, 
                      covariates = covariates,
                      max_iter = 10000,
                      max_prec = 1 / 1000000
                      )
  Vg_vec <- as.vector(cc_out$Vg)
  Ve_vec <- as.vector(cc_out$Ve)
  out <- tibble::as_tibble(t(c(Vg_vec, Ve_vec)))
  out2 <- dplyr::rename(out, Vg11 = V1, Vg12 = V2, Vg21 = V3, Vg22 = V4, Ve11 = V5, Ve12 = V6, Ve21 = V7, Ve22 = V8)
  return(out2)
}

```

```{r}
get_vc(e1 = local_expr_mat[ , colnames(local_expr_mat) == hnf4a_id, drop = FALSE],
       e2 = hotspot_expr_mat[ , 1, drop = FALSE],
       kinship = k2,
       covariates = addcovar2[, 1:4]
       )
```

```{r}
vc <- hotspot_expr_mat %>%
  as_tibble() %>%
  purrr::map_dfr(get_vc,
                 e1 = local_expr_mat[ , colnames(local_expr_mat) == hnf4a_id,
                                      drop = FALSE],
                 kinship = k2,
                 covariates = addcovar2[ , 1:4]
                 )
```


```{r}
vc
saveRDS(vc, "../data/hnf4a-variance-components-tibble.rds")
```

